/**
 * `@cssdoc/tmlanguage` — a TextMate injection grammar that highlights cssdoc doc-comment tags inside
 * CSS comments, the way TSDoc highlights JSDoc tags inside `/** … *\/` comments. It layers onto the host
 * CSS grammar's comment scope, so `@component`, `@modifier`, `@cssproperty`, `{@link …}`, the release
 * modifiers, and custom properties light up wherever CSS is highlighted.
 *
 * The grammar is built from the canonical tag vocabulary in `@cssdoc/spec` via
 * {@link buildInjectionGrammar}, so the tag list is defined exactly once. The default export is the
 * grammar as a Shiki `LanguageRegistration` (it carries `injectTo`), so it drops into a Shiki or
 * VitePress config; the same grammar is also published as `./cssdoc.injection.tmLanguage.json`
 * (generated by `scripts/generate.mjs`, kept in sync by the tests) for VS Code's
 * `contributes.grammars` and other TextMate hosts.
 *
 * @example
 * ```ts
 * // .vitepress/config.ts
 * import cssdoc from "@cssdoc/tmlanguage";
 * export default { markdown: { languages: [cssdoc] } };
 * ```
 *
 * @module @cssdoc/tmlanguage
 */
import { CSSDOC_TAGS, cssdocTagNamesByArgument, cssdocTagNamesByKind } from "@cssdoc/spec";

/** A TextMate capture assignment (`{ "1": { name } }`). */
type Captures = Record<string, { name: string }>;

/** A TextMate pattern rule — a match rule, a begin/end rule, or a `#repository` reference. */
interface TmRule {
  name?: string;
  match?: string;
  begin?: string;
  end?: string;
  beginCaptures?: Captures;
  endCaptures?: Captures;
  captures?: Captures;
  patterns?: TmRule[];
  include?: string;
}

/** A TextMate injection grammar. */
export interface InjectionGrammar {
  $schema: string;
  name: string;
  scopeName: string;
  injectionSelector: string;
  patterns: TmRule[];
  repository: Record<string, TmRule>;
}

const TAG_SCOPE = "storage.type.class.cssdoc";
const alt = (names: readonly string[]): string => names.join("|");

/**
 * Build the cssdoc injection grammar from the canonical `@cssdoc/spec` vocabulary. The argument-bearing
 * tags (`@modifier`, `@part`/`@slot`, `@cssproperty`) get their own rules that also colour the token
 * that follows; the inline tags open a `{@link …}` rule; every other tag is a bare keyword.
 */
export function buildInjectionGrammar(): InjectionGrammar {
  const inlineTags = alt(cssdocTagNamesByKind("inline"));
  const modifierTags = alt(cssdocTagNamesByArgument("modifier-name"));
  const partTags = alt(cssdocTagNamesByArgument("part-name"));
  const propertyTags = alt(cssdocTagNamesByArgument("custom-property"));
  const blockTags = alt(
    CSSDOC_TAGS.filter((t) => t.kind !== "inline" && !t.argument).map((t) => t.name),
  );

  return {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    name: "cssdoc",
    scopeName: "documentation.cssdoc",
    injectionSelector: "L:comment.block.css, L:comment.block.scss, L:comment.block.less",
    patterns: [
      { include: "#inline-tag" },
      { include: "#modifier-tag" },
      { include: "#part-tag" },
      { include: "#property-tag" },
      { include: "#structure-tag" },
      { include: "#block-tag" },
      { include: "#custom-property" },
    ],
    repository: {
      "inline-tag": {
        name: "meta.inline-tag.cssdoc",
        begin: `(\\{)(@(?:${inlineTags}))\\b`,
        beginCaptures: {
          "1": { name: "punctuation.definition.tag.begin.cssdoc" },
          "2": { name: TAG_SCOPE },
        },
        end: "(\\})",
        endCaptures: { "1": { name: "punctuation.definition.tag.end.cssdoc" } },
        patterns: [
          { match: "\\|", name: "punctuation.separator.cssdoc" },
          { match: "[^}|]+", name: "markup.underline.link.cssdoc" },
        ],
      },
      "modifier-tag": {
        match: `(@(?:${modifierTags}))\\b[ \\t]*(-[A-Za-z][A-Za-z0-9-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "variable.other.modifier.cssdoc" },
        },
      },
      "part-tag": {
        match: `(@(?:${partTags}))\\b[ \\t]*(\\.?[A-Za-z][A-Za-z0-9_-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "entity.other.attribute-name.part.cssdoc" },
        },
      },
      "property-tag": {
        match: `(@(?:${propertyTags}))\\b[ \\t]*(--[A-Za-z][A-Za-z0-9-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "support.type.custom-property.cssdoc" },
        },
      },
      "block-tag": {
        match: `(@(?:${blockTags}))\\b`,
        name: TAG_SCOPE,
      },
      // The `@structure` body is nested CSS. We light up only the parts (class selectors) and the
      // braces that show nesting — not a full CSS grammar. The region runs to the next tag or the
      // comment's end. Listed before `#block-tag` so it claims `@structure` first.
      "structure-tag": {
        begin: "(@structure)\\b",
        beginCaptures: { "1": { name: TAG_SCOPE } },
        end: "(?=@)|(?=\\*/)",
        patterns: [
          {
            match: "\\.[A-Za-z][A-Za-z0-9_-]*",
            name: "entity.other.attribute-name.part.cssdoc",
          },
          { match: "[{}]", name: "punctuation.section.structure.cssdoc" },
        ],
      },
      "custom-property": {
        match: "(?<![\\w-])--[A-Za-z][A-Za-z0-9-]*",
        name: "support.type.custom-property.cssdoc",
      },
    },
  };
}

/** The scopes the injection layers onto (CSS, plus SCSS/Less and CSS embedded in HTML `<style>`). */
export const injectTo = ["source.css", "source.scss", "source.less"];

/** The cssdoc doc-comment injection grammar, shaped as a Shiki `LanguageRegistration`. */
export const cssdoc = { ...buildInjectionGrammar(), injectTo };

export default cssdoc;
