/**
 * `@cssdoc/tmlanguage` — a TextMate injection grammar that highlights cssdoc doc-comment tags inside
 * CSS comments, the way TSDoc highlights JSDoc tags inside `/** … *\/` comments. It layers onto the host
 * CSS grammar's comment scope, so `@component`, `@modifier`, `@cssproperty`, `{@link …}`, the release
 * modifiers, and custom properties light up wherever CSS is highlighted.
 *
 * The grammar is built from the canonical tag vocabulary in `@cssdoc/spec` via
 * {@link buildInjectionGrammar}, so the tag list is defined exactly once. The default export is the
 * grammar as a Shiki `LanguageRegistration` (it carries `injectTo`), so it drops into a Shiki or
 * VitePress config; the same grammar is also published as `./cssdoc.injection.tmLanguage.json`
 * (generated by `scripts/generate.mjs`, kept in sync by the tests) for VS Code's
 * `contributes.grammars` and other TextMate hosts.
 *
 * @example
 * ```ts
 * // .vitepress/config.ts
 * import cssdoc from "@cssdoc/tmlanguage";
 * export default { markdown: { languages: [cssdoc] } };
 * ```
 *
 * @module @cssdoc/tmlanguage
 */
import { CSSDOC_TAGS, cssdocTagNamesByArgument, cssdocTagNamesByKind } from "@cssdoc/spec";

/** A TextMate capture assignment (`{ "1": { name } }`). */
type Captures = Record<string, { name: string }>;

/** A TextMate pattern rule — a match rule, a begin/end rule, or a `#repository` reference. */
interface TmRule {
  name?: string;
  match?: string;
  begin?: string;
  end?: string;
  beginCaptures?: Captures;
  endCaptures?: Captures;
  captures?: Captures;
  patterns?: TmRule[];
  include?: string;
}

/** A TextMate injection grammar. */
export interface InjectionGrammar {
  $schema: string;
  name: string;
  scopeName: string;
  injectionSelector: string;
  patterns: TmRule[];
  repository: Record<string, TmRule>;
}

/** A Shiki/VS Code registration: grammar + inject targets. */
export interface InjectionLanguageRegistration extends InjectionGrammar {
  injectTo: string[];
}

const TAG_SCOPE = "storage.type.class.cssdoc";
const alt = (names: readonly string[]): string => names.join("|");

/**
 * Build the cssdoc injection grammar from the canonical `@cssdoc/spec` vocabulary. The argument-bearing
 * tags (`@modifier`, `@part`/`@slot`, `@cssproperty`) get their own rules that also colour the token
 * that follows; the inline tags open a `{@link …}` rule; every other tag is a bare keyword.
 */
export function buildInjectionGrammar(): InjectionGrammar {
  const inlineTags = alt(cssdocTagNamesByKind("inline"));
  const recordTags = alt(cssdocTagNamesByKind("record"));
  const modifierTags = alt(cssdocTagNamesByArgument("modifier-name"));
  const partTags = alt(cssdocTagNamesByArgument("part-name"));
  const propertyTags = alt(cssdocTagNamesByArgument("custom-property"));
  // Everything argument-less that isn't a record tag or `@cssstate` — those get their own value-colouring
  // rules below (a record's name, a state's `:state(…)`), so they must not fall through to the bare
  // keyword rule.
  const blockTags = alt(
    CSSDOC_TAGS.filter(
      (t) => t.kind !== "inline" && t.kind !== "record" && t.name !== "cssstate" && !t.argument,
    ).map((t) => t.name),
  );

  return {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    name: "cssdoc",
    scopeName: "documentation.cssdoc",
    injectionSelector: "L:comment.block.css, L:comment.block.scss, L:comment.block.less",
    patterns: [
      { include: "#inline-tag" },
      { include: "#record-tag" },
      { include: "#modifier-tag" },
      { include: "#part-tag" },
      { include: "#property-tag" },
      { include: "#ref-tag" },
      { include: "#state-tag" },
      { include: "#structure-tag" },
      { include: "#block-tag" },
      { include: "#custom-property" },
    ],
    repository: {
      "inline-tag": {
        name: "meta.inline-tag.cssdoc",
        begin: `(\\{)(@(?:${inlineTags}))\\b`,
        beginCaptures: {
          "1": { name: "punctuation.definition.tag.begin.cssdoc" },
          "2": { name: TAG_SCOPE },
        },
        end: "(\\})",
        endCaptures: { "1": { name: "punctuation.definition.tag.end.cssdoc" } },
        patterns: [
          { match: "\\|", name: "punctuation.separator.cssdoc" },
          { match: "[^}|]+", name: "markup.underline.link.cssdoc" },
        ],
      },
      // A record's name (`@component button`) reads like a type name. Listed before the bare keyword
      // rule so it claims the tag and colours the identifier that follows.
      "record-tag": {
        match: `(@(?:${recordTags}))\\b[ \\t]*(\\.?[A-Za-z][A-Za-z0-9_-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "entity.name.type.cssdoc" },
        },
      },
      // Modifiers are spelled many ways (`-color-secondary`, `button--secondary`, `primary`); colour the
      // whole name, using the same scope as parts so a component's members read consistently.
      "modifier-tag": {
        match: `(@(?:${modifierTags}))\\b[ \\t]*(-?[A-Za-z][A-Za-z0-9_-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "entity.other.attribute-name.part.cssdoc" },
        },
      },
      // `@cssstate :state(open)` / `@cssstate :disabled` — colour the state token like a custom property.
      "state-tag": {
        match: "(@(?:cssstate))\\b[ \\t]*(:?[A-Za-z][A-Za-z0-9_-]*(?:\\([A-Za-z0-9_-]*\\))?)?",
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "support.type.custom-property.cssdoc" },
        },
      },
      "part-tag": {
        match: `(@(?:${partTags}))\\b[ \\t]*(\\.?[A-Za-z][A-Za-z0-9_-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "entity.other.attribute-name.part.cssdoc" },
        },
      },
      "property-tag": {
        match: `(@(?:${propertyTags}))\\b[ \\t]*(--[A-Za-z][A-Za-z0-9-]*)?`,
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "support.type.custom-property.cssdoc" },
        },
      },
      // `@ref 1` / `@ref 1.` — numeric annotation reference index.
      "ref-tag": {
        match: "(@(?:ref))\\b[ \\t]*(\\d+\\.?)?",
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "constant.numeric.cssdoc" },
        },
      },
      "block-tag": {
        match: `(@(?:${blockTags}))\\b`,
        name: TAG_SCOPE,
      },
      // The `@structure` body is nested CSS. We light up only the parts (class selectors) and the
      // braces that show nesting — not a full CSS grammar. The region runs to the next tag or the
      // comment's end. Listed before `#block-tag` so it claims `@structure` first.
      "structure-tag": {
        begin: "(@structure)\\b",
        beginCaptures: { "1": { name: TAG_SCOPE } },
        end: "(?=@)|(?=\\*/)",
        patterns: [
          {
            match: "\\.[A-Za-z][A-Za-z0-9_-]*",
            name: "entity.other.attribute-name.part.cssdoc",
          },
          { match: "[{}]", name: "punctuation.section.structure.cssdoc" },
        ],
      },
      "custom-property": {
        match: "(?<![\\w-])--[A-Za-z][A-Za-z0-9-]*",
        name: "support.type.custom-property.cssdoc",
      },
    },
  };
}

/**
 * Build an injection grammar that highlights cssdoc record-reference at-rules in source CSS, for
 * examples like `@component top-nav (--desktop-nav) {}` used inside implicit layout blocks.
 */
export function buildAtRuleInjectionGrammar(): InjectionGrammar {
  const recordTags = alt(cssdocTagNamesByKind("record"));
  const nativeCssAtRules = alt([
    "charset",
    "color-profile",
    "container",
    "counter-style",
    "document",
    "font-face",
    "font-feature-values",
    "font-palette-values",
    "import",
    "keyframes",
    "layer",
    "media",
    "namespace",
    "page",
    "property",
    "scope",
    "starting-style",
    "supports",
    "view-transition",
  ]);
  return {
    $schema: "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    name: "cssdoc-at-rules",
    scopeName: "source.css.cssdoc.atrules",
    injectionSelector: "L:meta.at-rule.css, L:meta.at-rule.scss, L:meta.at-rule.less",
    patterns: [
      { include: "#record-ref-atrule" },
      { include: "#untyped-ref-atrule" },
      { include: "#custom-property" },
    ],
    repository: {
      // Typed record refs: @component nav, @layout shell, with optional :profile / (--profile).
      "record-ref-atrule": {
        match:
          `(@(?:${recordTags}))\\b(?:[ \\t]+([A-Za-z][A-Za-z0-9_-]*))?` +
          "(?:[ \\t]+(\\(\\s*--[A-Za-z][A-Za-z0-9-]*\\s*\\)|:[A-Za-z][A-Za-z0-9_-]*))?",
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "entity.name.type.cssdoc" },
          "3": { name: "support.type.custom-property.cssdoc" },
        },
      },
      // Untyped refs: @nav / @header, with optional profile marker. Excludes native CSS at-rules.
      "untyped-ref-atrule": {
        match:
          `(@(?!(?:${nativeCssAtRules})\\b)(?:[A-Za-z][A-Za-z0-9_-]*))` +
          "(?:[ \\t]+(\\(\\s*--[A-Za-z][A-Za-z0-9-]*\\s*\\)|:[A-Za-z][A-Za-z0-9_-]*))?",
        captures: {
          "1": { name: TAG_SCOPE },
          "2": { name: "support.type.custom-property.cssdoc" },
        },
      },
      "custom-property": {
        match: "(?<![\\w-])--[A-Za-z][A-Za-z0-9-]*",
        name: "support.type.custom-property.cssdoc",
      },
    },
  };
}

/**
 * The host scopes the injection layers onto. It fires only where `comment.block.css` (etc.) appears —
 * see {@link InjectionGrammar.injectionSelector} — so listing the JS/HTML/Markdown/framework hosts is
 * safe: cssdoc lights up embedded CSS wherever another grammar embeds it, not just in `.css` files.
 */
export const injectTo = [
  "source.css",
  "source.scss",
  "source.less",
  "source.css.styled",
  "source.ts",
  "source.tsx",
  "source.js",
  "source.jsx",
  "source.vue",
  "source.svelte",
  "source.astro",
  "text.html.markdown",
  "text.html.basic",
  "text.html.derivative",
];

/** The cssdoc doc-comment injection grammar, shaped as a Shiki `LanguageRegistration`. */
export const cssdoc: InjectionLanguageRegistration = { ...buildInjectionGrammar(), injectTo };

/** The cssdoc record-ref at-rule injection grammar for source CSS. */
export const cssdocAtRules: InjectionLanguageRegistration = {
  ...buildAtRuleInjectionGrammar(),
  injectTo,
};
export default cssdoc;
