import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import grammarkdown from "@cssdoc/grammarkdown-tmlanguage";
import cssdoc from "@cssdoc/tmlanguage";
import type { DefaultTheme } from "vitepress";
import { defineConfig } from "vitepress";
import { mermaidPlugin } from "./plugins/vitepress-mermaid/index.js";

// The site is served at its own apex domain (cssdoc.dev), so it lives at the root. DOCS_BASE can still
// override this (e.g. to preview under a project-pages subpath).
const base = process.env.DOCS_BASE ?? "/";

// The API reference sidebar is generated by `docs:api` (typedoc + typedoc-vitepress-theme). Read it if
// present so `vitepress dev` still loads before the first generation; `docs:dev`/`docs:build` run
// typedoc first, so it's there for real builds.
const apiSidebarPath = fileURLToPath(new URL("../reference/typedoc-sidebar.json", import.meta.url));
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(apiSidebarPath)
  ? (JSON.parse(readFileSync(apiSidebarPath, "utf8")) as DefaultTheme.SidebarItem[])
  : [];

export default defineConfig({
  base,
  lang: "en-US",
  title: "cssdoc",
  description: "TSDoc, for CSS — document CSS with structured comments.",
  cleanUrls: true,
  sitemap: { hostname: "https://cssdoc.dev" },
  // Register the grammarkdown grammar (for the Grammar page) and the cssdoc injection grammar (so CSS
  // examples highlight their doc-comment tags, the way TSDoc does).
  markdown: {
    languages: [grammarkdown, cssdoc],
    config: (md) => {
      md.use(mermaidPlugin);
    },
  },
  head: [
    ["link", { rel: "icon", href: `${base}icon.svg` }],
    ["link", { rel: "icon", media: "(prefers-color-scheme: dark)", href: `${base}icon-dark.svg` }],
  ],
  themeConfig: {
    footer: {
      message: "Released under the MIT License",
      copyright: "Copyright © 2026-present <a href='https://iywahl.com' target='_blank'>iyWahl</a>",
    },
    logo: { light: "/icon.svg", dark: "/icon-dark.svg" },
    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "Packages", link: "/guide/packages" },
      { text: "API Reference", link: "/reference/" },
    ],
    sidebar: {
      "/reference/": apiSidebar,
      "/": [
        {
          text: "Guide",
          items: [
            { text: "Introduction", link: "/guide/introduction" },
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Authoring doc comments", link: "/guide/authoring" },
            { text: "Modifier conventions", link: "/guide/modifier-conventions" },
            { text: "Configuration", link: "/guide/config" },
            { text: "Embedded CSS", link: "/guide/embedded-css" },
            { text: "Emitting docs", link: "/guide/emitters" },
            { text: "Standard formats", link: "/guide/generators" },
            { text: "Linting", link: "/guide/linting" },
            { text: "Editor support", link: "/guide/editor" },
          ],
        },
        {
          text: "Reference",
          items: [
            { text: "Playground", link: "/guide/playground" },
            { text: "Packages", link: "/guide/packages" },
            { text: "Grammar", link: "/guide/grammar" },
            { text: "API Reference", link: "/reference/" },
          ],
        },
      ],
    },
    outline: "deep",
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/thedannywahl/cssdoc/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/thedannywahl/cssdoc" }],
  },
});
