import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import grammarkdown from "@cssdoc/grammarkdown-tmlanguage";
import cssdoc from "@cssdoc/tmlanguage";
import type { DefaultTheme } from "vitepress";
import { defineConfig } from "vitepress";
import llmstxt from "vitepress-plugin-llms";
import { mermaidPlugin } from "./plugins/vitepress-mermaid/index.js";

// The site is served at its own apex domain (cssdoc.dev), so it lives at the root. DOCS_BASE can still
// override this (e.g. to preview under a project-pages subpath).
const base = process.env.DOCS_BASE ?? "/";

// Canonical origin, used for the sitemap, per-page canonical links, and absolute social-card URLs.
const hostname = "https://cssdoc.dev";

// One site-wide description, ~139 chars — a subset of the home hero tagline, long enough for social
// unfurl previews (which want 120–140). Feeds the meta description, Open Graph, Twitter, and JSON-LD.
const description =
  "Document CSS with comments — parse them plus the CSS AST into a model, then emit docs, catch drift and misuse, and get editor IntelliSense.";

// The API reference sidebar is generated by `docs:api` (typedoc + typedoc-vitepress-theme). Read it if
// present so `vitepress dev` still loads before the first generation; `docs:dev`/`docs:build` run
// typedoc first, so it's there for real builds.
const apiSidebarPath = fileURLToPath(new URL("../reference/typedoc-sidebar.json", import.meta.url));
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(apiSidebarPath)
  ? (JSON.parse(readFileSync(apiSidebarPath, "utf8")) as DefaultTheme.SidebarItem[])
  : [];

export default defineConfig({
  base,
  lang: "en-US",
  title: "cssdoc",
  description,
  cleanUrls: true,
  sitemap: { hostname },
  // Emit /llms.txt (an agent-legible index) and /llms-full.txt (the whole site as one document) at the
  // dist root, so AI agents can read cssdoc without scraping HTML. Covers the guide pages and the
  // generated API reference.
  vite: {
    // The repo aliases `vite` to vite-plus-core, but VitePress types this field against upstream Vite,
    // and llmstxt() carries a third Vite's Plugin types — three incompatible `PluginOption`s. The plugin
    // works at runtime; cast through the bottom type to bridge the type identities.
    plugins: [
      llmstxt({
        title: "cssdoc",
        description,
      }) as never,
    ],
  },
  // Register the grammarkdown grammar (for the Grammar page) and the cssdoc injection grammar (so CSS
  // examples highlight their doc-comment tags, the way TSDoc does).
  markdown: {
    languages: [grammarkdown, cssdoc],
    config: (md) => {
      md.use(mermaidPlugin);
    },
  },
  head: [
    ["link", { rel: "icon", href: `${base}icon.svg` }],
    ["link", { rel: "icon", media: "(prefers-color-scheme: dark)", href: `${base}icon-dark.svg` }],
    ["meta", { name: "author", content: "Danny Wahl" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "CSS, CSS documentation, doc comments, TSDoc, design tokens, linting, stylelint, language server, IntelliSense, VS Code",
      },
    ],
    // Social-card defaults so cssdoc.dev links unfurl into rich previews (Slack, iMessage, X,
    // LinkedIn, Discord, Facebook). Per-page title/description/url are layered on in transformHead.
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "cssdoc" }],
    ["meta", { property: "og:locale", content: "en_US" }],
    ["meta", { property: "og:image", content: `${hostname}/og.png` }],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    ["meta", { property: "og:image:alt", content: "cssdoc — TSDoc, for CSS" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    ["meta", { name: "twitter:site", content: "@thedannywahl" }],
    ["meta", { name: "twitter:creator", content: "@thedannywahl" }],
    ["meta", { name: "twitter:image", content: `${hostname}/og.png` }],
    ["meta", { name: "twitter:image:alt", content: "cssdoc — TSDoc, for CSS" }],
    // Schema.org structured data describing the site and its author.
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: "cssdoc",
        url: hostname,
        description,
        image: `${hostname}/og.png`,
        author: { "@type": "Person", name: "Danny Wahl", url: "https://iywahl.com" },
      }),
    ],
  ],
  // Layer per-page Open Graph / Twitter tags and a canonical link on top of the head defaults, so each
  // shared URL previews with its own title, description, and address rather than the site-wide default.
  transformHead: ({ pageData, siteData }) => {
    // The home page has no title of its own (the hero renders it), so give it a fuller line than the
    // bare site name — home is the most-shared URL and unfurls better with the tagline attached.
    const title =
      pageData.frontmatter.layout === "home"
        ? "cssdoc — TSDoc, for CSS"
        : pageData.frontmatter.title || pageData.title || siteData.title;
    const description =
      pageData.frontmatter.description || pageData.description || siteData.description;
    // relativePath is like "guide/introduction.md" or "index.md"; cleanUrls drops the extension and
    // index files map to their directory root.
    const url = `${hostname}/${pageData.relativePath}`
      .replace(/index\.md$/, "")
      .replace(/\.md$/, "");
    return [
      ["link", { rel: "canonical", href: url }],
      ["meta", { property: "og:title", content: title }],
      ["meta", { property: "og:description", content: description }],
      ["meta", { property: "og:url", content: url }],
      ["meta", { name: "twitter:title", content: title }],
      ["meta", { name: "twitter:description", content: description }],
    ];
  },
  themeConfig: {
    footer: {
      message: "Released under the MIT License",
      copyright: "Copyright © 2026-present <a href='https://iywahl.com' target='_blank'>iyWahl</a>",
    },
    logo: { light: "/icon.svg", dark: "/icon-dark.svg" },
    nav: [
      { text: "Guide", link: "/guide/introduction" },
      { text: "Packages", link: "/guide/packages" },
      { text: "API Reference", link: "/reference/" },
    ],
    sidebar: {
      "/reference/": apiSidebar,
      "/": [
        {
          text: "Guide",
          items: [
            { text: "Introduction", link: "/guide/introduction" },
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Authoring doc comments", link: "/guide/authoring" },
            { text: "Modifier conventions", link: "/guide/modifier-conventions" },
            { text: "Configuration", link: "/guide/config" },
            { text: "Embedded CSS", link: "/guide/embedded-css" },
            { text: "Emitting docs", link: "/guide/emitters" },
            { text: "Standard formats", link: "/guide/generators" },
            { text: "Linting", link: "/guide/linting" },
            { text: "Editor support", link: "/guide/editor" },
          ],
        },
        {
          text: "Reference",
          items: [
            { text: "Playground", link: "/guide/playground" },
            { text: "Packages", link: "/guide/packages" },
            { text: "Grammar", link: "/guide/grammar" },
            { text: "API Reference", link: "/reference/" },
          ],
        },
      ],
    },
    outline: "deep",
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/thedannywahl/cssdoc/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [
      {
        icon: {
          svg: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/></svg>',
        },
        link: "/llms.txt",
        ariaLabel: "llms.txt — documentation for AI agents",
      },
      { icon: "github", link: "https://github.com/thedannywahl/cssdoc" },
    ],
  },
});
