import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { DefaultTheme } from "vitepress";
import { defineConfig } from "vitepress";

// GitHub Pages serves a project site under /<repo>/. Override with DOCS_BASE if the repo name differs.
const base = process.env.DOCS_BASE ?? "/cssdoc/";

// The API reference sidebar is generated by `docs:api` (typedoc + typedoc-vitepress-theme). Read it if
// present so `vitepress dev` still loads before the first generation; `docs:dev`/`docs:build` run
// typedoc first, so it's there for real builds.
const apiSidebarPath = fileURLToPath(new URL("../reference/typedoc-sidebar.json", import.meta.url));
const apiSidebar: DefaultTheme.SidebarItem[] = existsSync(apiSidebarPath)
  ? (JSON.parse(readFileSync(apiSidebarPath, "utf8")) as DefaultTheme.SidebarItem[])
  : [];

export default defineConfig({
  base,
  lang: "en-US",
  title: "cssdoc",
  description: "TSDoc, for CSS — document CSS with structured comments.",
  cleanUrls: true,
  head: [
    ["link", { rel: "icon", href: `${base}icon.svg` }],
    ["link", { rel: "icon", media: "(prefers-color-scheme: dark)", href: `${base}icon-dark.svg` }],
  ],
  themeConfig: {
    logo: { light: `${base}icon.svg`, dark: `${base}icon-dark.svg` },
    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "Packages", link: "/guide/packages" },
      { text: "API Reference", link: "/reference/" },
    ],
    sidebar: {
      "/reference/": apiSidebar,
      "/": [
        {
          text: "Guide",
          items: [
            { text: "Introduction", link: "/guide/introduction" },
            { text: "Getting started", link: "/guide/getting-started" },
            { text: "Authoring doc comments", link: "/guide/authoring" },
            { text: "Configuration", link: "/guide/config" },
            { text: "Emitting docs", link: "/guide/emitters" },
            { text: "Standard formats", link: "/guide/generators" },
            { text: "Linting", link: "/guide/linting" },
            { text: "Editor support", link: "/guide/editor" },
          ],
        },
        {
          text: "Reference",
          items: [
            { text: "Packages", link: "/guide/packages" },
            { text: "Grammar", link: "/guide/grammar" },
            { text: "API Reference", link: "/reference/" },
          ],
        },
      ],
    },
    outline: "deep",
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/thedannywahl/cssdoc/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/thedannywahl/cssdoc" }],
  },
});
